### ISSUE TITLE
Throwing exception on requestHint() 

### ISSUE THREAD

**Issue by champ96k** [nikhilbiju67/phone_number_hint#4]
Getting this error when  i hit request hint 

`  final PhoneNumberHint _phoneNumberHintPlugin = PhoneNumberHint();
        final String _phoneNumber = await _phoneNumberHintPlugin.requestHint() ?? "";`

```dart
12-12 17:22:27.403 14680 14680 D InputMethodManager: showSoftInput() view=io.flutter.embedding.android.FlutterView{c6d4b69 VFE...... .F....ID 0,0-1080,2337 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
12-12 17:22:27.409 14680 14680 E MethodChannel#phone_number_hint: 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:18)
12-12 17:22:27.409 14680 14680 E MethodChannel#phone_number_hint: 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:19)
12-12 17:22:27.409 14680 14680 E MethodChannel#phone_number_hint: 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:42)
12-12 17:22:27.409 14680 14680 E MethodChannel#phone_number_hint: 	at io.flutter.embedding.engine.dart.DartMessenger.a(DartMessenger.java:1)
12-12 17:22:27.409 14680 14680 E MethodChannel#phone_number_hint: 	at io.flutter.embedding.engine.dart.a.run(R8$$SyntheticClass:13)
12-12 17:22:27.409 14680 14738 I flutter : Error in getting phone number hint catch : PlatformException(error, null, null, java.lang.NullPointerException
```

**Comment by champ96k** [comment]
Update: I just created created new package to show google phone number hint  - https://pub.dev/packages/google_phone_number_hint

Closing this issue
